name: rdf
channels:
  - conda-forge
dependencies:
  - python >3.8
  - pyscal3 =3.1.1
  - rdflib
  - pyyaml
  - jupyterlab
  - graphviz
  - python-graphviz
  - pyyaml
  - ase 
  - ipycytoscape
  - networkx
  - pandas
  - owlready2
