name: workflow-rdf-v0.2
channels:
  - conda-forge
dependencies:
  - python >3.8, <3.12
  - pyscal3 >=3.1.12
  - pyscal-rdf
  - rdflib
  - pyyaml
  - jupyterlab
  - graphviz
  - python-graphviz
  - ase 
  - networkx
  - pandas
  - owlready2
  - plotly
  - ipywidgets
  - atomman
  #workflow packages
  - pyiron_base
  - pyiron_atomistics
  - pyiron-data
  - sqlalchemy
  - iprpy-data
  - sphinxdft >=2.7.0
  - sphinxdft-data
  - lammps
  - nglview
  - pip:
    - "git+https://github.com/RDFLib/rdflib-sqlalchemy.git@develop"

